# Generated by Django 6.0.6 on 2026-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
