# Generated by Django 6.0.6 on 2026-07-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
