# Generated by Django 6.0.6 on 2026-07-10 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        ("visits", "0002_visit_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prescription_number", models.CharField(max_length=50, unique=True)),
                ("medication_name", models.CharField(max_length=200)),
                ("active_substance", models.CharField(blank=True, max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField()),
                ("instructions", models.TextField(blank=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="animals.animal",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["issue_date"], name="prescriptio_issue_d_ea6b9b_idx"
                    ),
                    models.Index(
                        fields=["prescription_number"],
                        name="prescriptio_prescri_de216a_idx",
                    ),
                ],
            },
        ),
    ]
