# Generated by Django 6.0.6 on 2026-07-08 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
        ("vaccinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="vaccination",
            index=models.Index(
                fields=["vaccination_date"], name="vaccination_vaccina_745d53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccination",
            index=models.Index(
                fields=["next_due_date"], name="vaccination_next_du_2be640_idx"
            ),
        ),
    ]
